name: TypeScript - E2E Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'typescript/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: typescript

jobs:
  test:
    name: Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and Start Ollama Server
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo sh
          ollama serve &
          sleep 5
          curl -s http://localhost:11434

      - name: Pull LLMs
        run: ollama pull granite4:micro

      - name: Check LLMs
        run: ollama run granite4:micro "Hello" --hidethinking

      - run: mise use nodejs@${{ matrix.node-version }}
      - run: mise typescript:test:e2e && mise typescript:test:examples
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_SEARCH_CSE_ID }}
          # AZURE_OPENAI_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
          # AZURE_OPENAI_API_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_API_DEPLOYMENT }}
          # AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          # AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
          WATSONX_REGION: ${{ secrets.WATSONX_REGION }}
          # WATSONX_SPACE_ID: ${{ secrets.WATSONX_SPACE_ID }}
          # WATSONX_DEPLOYMENT_ID: ${{ secrets.WATSONX_DEPLOYMENT_ID }}
